language: python
os: linux
dist: bionic
python:
  - "3.7" # current default Python on Travis CI
install:
  - pip install -e . # install deepreg package with corresponding requirements
  - pip install codecov
  - pre-commit install

jobs:
  include:
    - stage: "Linting and Docs"
      name: "Pre-commit"
      script:
        - black --check .
        - flake8 .
        - pre-commit run --all-files
    - name: "Sphinx Build"
      script:
        - cd docs
        - make clean html
    - stage: "Tests"
      name: "Unit Tests"
      script: pytest --cov-report= --cov=deepreg ./test/unit/
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: "Command Tests: Unpaired Unlabeled"
      script:
        - deepreg_train -g "" --config_path config/unpaired_labeled_ddf.yaml --log_dir test
        - deepreg_predict -g "" --ckpt_path logs/test/save/weights-epoch2.ckpt --mode test -b 3
        - deepreg_warp --image data/test/nifti/unit_test/moving_image.nii.gz --ddf data/test/nifti/unit_test/ddf.nii.gz --out logs/test_warp/out.nii.gz
